##########
# collectionbuilder-contentdm
# Jekyll Digital Collection Generator, designed as a skin over CONTENTdm
# https://github.com/CollectionBuilder/collectionbuilder-contentdm
##########

##########
# URL VARIABLES
#
# site domain, full URL to the production location of your collection
url: https://Temoshee.github.io
# path to location on the domain if necessary e.g. /digital/hjccc
baseurl: /lmdigitalstatic2
# location of code, the full url to your github repository
source-code: https://github.com/Temoshee

##########
# SITE SETTINGS
#
# title of site appears in banner
title: Requested bill analyses, bills, journal entries
# tagline, a short phrase that will appear throughout the site in the top banner
tagline: Michigan legislative history documents
# description appears in meta tags and other locations
# this description might appear in search result lists, keep around 160 characters max
description: "The State Law Library frequently scans paper documents to PDF format in response to library patron requests. Rather than delete them we put them here." 
# keywords, a short list of subjects describing the collection, separated by semicolon, to appear in rich markup
# keywords: idaho;history;inland northwest 
# creator of the digital collection, to appear in meta tags; we typically use our GitHub usernames but feel free to just use your name
author: Timothy Watters
# Organization branding
organization-name: "Library of Michigan, State Law Library"
organization-link: https://lmdigital.libraryofmichigan.org/
organization-logo-banner: https://cdm16110.contentdm.oclc.org/customizations/global/images/logo.svg
organization-logo-nav: https://www.michigan.gov/images/libraryofmichigan/LM_2020_LM_Digital_Logo_rs_704422_7.PNG


##########
# COLLECTION SETTINGS
#
# choose metadata: this is the name of the csv file in your _data directory that describes the objects in your collection
metadata: lmdigitalstatic3
# contentdm collection name, matches collection ID used by CDM
cdm-collection-id: p16110coll6
# CONTENTdm server url
cdm-url: https://cdm16110.contentdm.oclc.org
# page generation settings 
# "data" value must be the name of the metadata file (other values should be not be changed)
page_gen:
  - data: 'lmdigitalstatic3'
    template: 'items'
    name: 'objectid'
    dir: 'items'
    extension: 'html' 
    filter: 'objectid'  

##########
# GOOGLE SERVICES [optional!]
#
# leave these blank or comment out to NOT include google code. See docs/google.md
#
# Add your google-analytics-id to automatically add the embed code, e.g. "UA-76328753-1"
# google-analytics-id:
# to populate a Google CSE add the id, e.g. "002151703305773322890:1pu3smhw1t8"
# google-cse-id: 

##########
# ROBOTS EXCLUDE
#
# set noindex to true if you do NOT want Google to index your site
noindex: true 

##########
# BUILD SETTINGS 
#
# Note: use environment variable on build command to include analytics
# JEKYLL_ENV=production jekyll build
# (this is done automatically by gh-pages build)
#
# ignore stuff
exclude: [docs/, Rakefile, README.md, LICENSE]
# compress CSS output
sass:
  style: compressed
